export const mock_data = [
	{
		scu: '4G180',
		description: 'Tenda 4G LTE 150Mbps Mobile WiFi Router | 4G180',
		cpt: 34,
		jhb: 70,
		dbn: 2,
		total_stock: 106,
		dealer_price: 750,
		retail_price: 952.17,
		manufacturer: 'Tenda',
		image_url: 'https://scoop.co.za/download/marketing/images/4G180.jpg'
	},
	{
		scu: '4G680',
		description: 'Tenda 4G LTE 300Mbps WiFi Router | 4G680',
		cpt: 0,
		jhb: 0,
		dbn: 0,
		total_stock: 0,
		dealer_price: 995,
		retail_price: 1252.17,
		manufacturer: 'Tenda',
		image_url: 'https://scoop.co.za/download/marketing/images/4G680.jpg'
	},
	{
		scu: 'ACB-AC',
		description: 'Ubiquiti AirCube AC WiFi Router | ACB-AC',
		cpt: 20,
		jhb: 101,
		dbn: 3,
		total_stock: 124,
		dealer_price: 1025,
		retail_price: 1282.61,
		manufacturer: 'Ubiquiti',
		image_url: 'https://scoop.co.za/download/marketing/images/ACB-AC.jpg'
	},
	{
		scu: 'ACB-ISP',
		description: 'Ubiquiti AirCube WiFi PoE Access Point with UNMS | ACB-ISP',
		cpt: 159,
		jhb: 107,
		dbn: 30,
		total_stock: 296,
		dealer_price: 395,
		retail_price: 478.26,
		manufacturer: 'Ubiquiti',
		image_url: 'https://scoop.co.za/download/marketing/images/ACB-ISP.jpg'
	},
	{
		scu: 'AF-11FX',
		description: 'Ubiquiti AirFiberX 11GHz PtP Radio | AF-11FX',
		cpt: 10,
		jhb: 43,
		dbn: 2,
		total_stock: 55,
		dealer_price: 8595,
		retail_price: 10691.3,
		manufacturer: 'Ubiquiti',
		image_url: 'https://scoop.co.za/download/marketing/images/AF-11FX.jpg'
	},
	{
		scu: 'AF-11FXDUPL',
		description: 'Ubiquiti AirFiberX 11Ghz Low Band Duplexer | AF-11FX-DUP-L',
		cpt: 21,
		jhb: 79,
		dbn: 2,
		total_stock: 102,
		dealer_price: 2650,
		retail_price: 3300.0,
		manufacturer: 'Ubiquiti',
		image_url: 'https://scoop.co.za/download/marketing/images/AF-11FXDUPL.jpg'
	},
	{
		scu: 'AF-11G35',
		description: 'Ubiquiti AirFiber Dish 11Ghz 35dBi 81cm | AF-11G35',
		cpt: 15,
		jhb: 56,
		dbn: 3,
		total_stock: 74,
		dealer_price: 5325,
		retail_price: 6652.17,
		manufacturer: 'Ubiquiti',
		image_url: 'https://scoop.co.za/download/marketing/images/AF-11G35.jpg'
	},
	{
		scu: 'AF-5XHD',
		description: 'Ubiquiti AirFiber5X HD PtP Radio Gigabit WiFi | AF-5XHD',
		cpt: 64,
		jhb: 117,
		dbn: 9,
		total_stock: 190,
		dealer_price: 5495,
		retail_price: 6865.22,
		manufacturer: 'Ubiquiti',
		image_url: 'https://scoop.co.za/download/marketing/images/AF-5XHD.jpg'
	},
	{
		scu: 'AFI-INSK',
		description: 'Ubiquiti AmpliFi Instant Router +1 MeshPoint Kit | AFI-INS',
		cpt: 37,
		jhb: 113,
		dbn: 5,
		total_stock: 155,
		dealer_price: 2495,
		retail_price: 3126.09,
		manufacturer: 'Ubiquiti',
		image_url: 'https://scoop.co.za/download/marketing/images/AFI-INSK.jpg'
	},
	{
		scu: 'AFI-INSR',
		description: 'Ubiquiti AmpliFi Instant Router | AFI-INS-R',
		cpt: 23,
		jhb: 52,
		dbn: 3,
		total_stock: 78,
		dealer_price: 1375,
		retail_price: 1717.39,
		manufacturer: 'Ubiquiti',
		image_url: 'https://scoop.co.za/download/marketing/images/AFI-INSR.jpg'
	},
	{
		scu: 'AIR-D523X',
		description: 'Ubiquiti 5GHz AirFiber Dish 23dBi Slant 45 PtP | AF-5G23-S45',
		cpt: 16,
		jhb: 36,
		dbn: 5,
		total_stock: 57,
		dealer_price: 1450,
		retail_price: 1821.74,
		manufacturer: 'Ubiquiti',
		image_url: 'https://scoop.co.za/download/marketing/images/AIR-D523X.jpg'
	},
	{
		scu: 'AIR-D530',
		description: 'Ubiquiti 5GHz AirMax Dish 30dBi Backhaul PtP | RD-5G30',
		cpt: 17,
		jhb: 18,
		dbn: 5,
		total_stock: 40,
		dealer_price: 1850,
		retail_price: 2304.35,
		manufacturer: 'Ubiquiti',
		image_url: 'https://scoop.co.za/download/marketing/images/AIR-D530.jpg'
	},
	{
		scu: 'AIR-D530LW',
		description: 'Ubiquiti 5GHz AirMax Dish 30dBi Light Weight PtP | RD-5G30-LW',
		cpt: 62,
		jhb: 243,
		dbn: 16,
		total_stock: 321,
		dealer_price: 1395,
		retail_price: 1734.78,
		manufacturer: 'Ubiquiti',
		image_url: 'https://scoop.co.za/download/marketing/images/AIR-D530LW.jpg'
	}
]
